### PR TITLE
full async validation support

### PR DESCRIPTION
**Pull request by pibi**
following https://github.com/zhaoyao91/moleculer-json-schema-validator/pull/3, this is a full implementation based on the current validator base class, plus the options support fro AJV.

### CODE REVIEW

**Comment by pibi** [comment]
@zhaoyao91 With this PR the validator is compatible with the middleware semantics, which officially supports async. I would keep this feature on my fork, but what do you think to just add the options support to your release? this way I can use the AJV options for the microservices that do not need the async validator.

**Comment by zhaoyao91** [comment]
Why do you override `middleware` method? It is defined in the base validator, and I didn't notice any nessesary to override it.

BTW, if you just want to use customized ajv instance, you could new one and assign it to the `ajvValidator.validator`.

see https://github.com/zhaoyao91/moleculer-json-schema-validator/blob/master/index.js#L9

**Comment by pibi** [comment]
the override of the `middleware` method is necessary if you want an officially supported async module. 
I would rather pass the settings from the validator constructor than "ovveride" the default one.

**Comment by zhaoyao91** [comment]
I am confused ... is the added `middleware` method the same as the one in `BaseValidator`?

**Comment by pibi** [comment]
No, see https://github.com/zhaoyao91/moleculer-json-schema-validator/pull/4/files#diff-168726dbe96b3ce427e7fedce31bb0bcR33-R34 vs https://github.com/moleculerjs/moleculer/blob/master/src/validator.js#L45-L46 

With my change the validator is now a middleware fully complaint with the contract of the middlewares for the moleculer project. This should solve your argument in #3 .

**Comment by zhaoyao91** [comment]
I see, you make `validateContextParams` async, so it will return a promise. But there is no evidence that the moleculer would invoke this function this way.

**Comment by pibi** [comment]
I don't understand. the broker calls an action asynchronously by default, it cannot be different especially if you are calling a remote service. Indeed, the `broker.call` returns a `Promise` :  https://moleculer.services/docs/0.13/broker.html#Methods 

Internally, the middleware module calls every middleware as a thenable function: https://github.com/moleculerjs/moleculer/blob/master/src/middleware.js#L72 .

**Comment by zhaoyao91** [comment]
Sorry, I am not actively using moleculer this time, having less time to dig deep.

I can't take the risk to implement a feature that is not comply with the explicit API or demo and relying on the implementation details.

I advise you to fork a local customized version if it's nessesary for you.

**Comment by pibi** [comment]
No problem, I understand your point. This PR is implementing the validator as per the explicit middleware APIs (https://moleculer.services/docs/0.13/middlewares.html), I linked you to the implementation detail to give you a deeper insight.

I will release a proper fork of this soon, but for everyone interested, here is a link to my repo to be used in the package.json: https://github.com/pibi/moleculer-json-schema-validator.git#semver:1.1.0

**Pull request closed without merging**
